### ISSUE TITLE
Throw error or handle name vs bundle mismatch

### ISSUE THREAD

**Issue by bweissbart** [brandingbrand/flagship#662] opened 2019-05-29 15:14 UTC
Currently, if the `name` property in the environment configuration doesn't match the last value in the `bundleIds.android` property, running Android will lead to a MainActivity not found error. We should either add an error if name.toLowerCase() doesn't equal the last token of `bundleIds.android`, or better figure out where this is being created and find a better solution.

For example, if name is set to 'TestApp' and the bundleId is set to 'com.brandingbrand.test', the error is: `Activity class {com.brandingbrand.testapp/com.brandingbrand.testapp.MainActivity} does not exist.`

**Comment by nathan-sankbeil** [comment] 2019-09-24 19:56
Duplicate of https://github.com/brandingbrand/flagship/issues/258

**Closed by nathan-sankbeil** 2019-09-24 19:56 UTC
